### ISSUE TITLE
Panel with info not opening on Safari

### ISSUE THREAD

**Issue by marksweiss** [lachlanjc/calltoaction#39]
Version 9.0.2 (11601.3.9)
OSX 10.11.2

Opens on Chrome, not on Safari.

**Comment by marksweiss** [comment]
/**
    	 * Render the passed-in representative card HTML
    	 * @param  {string} templateString
    	 */
    renderRepresentativeCard: function(templateString) {
        templateString || (templateString = app.devDummyData);
        var repContainer = document.getElementById('repContentContainer');
        var repCardList = document.getElementById('repList');

        // Remove hidden class

// ----> FAILING HERE <----
// "Attempt to assign to readonly property"
// So `classList` is being treated as readonly on Safari

        repContainer && (repContainer.classList = '');

        // Add rep-card to page
        repCardList.innerHTML = templateString;
    },

**Comment by MitulP91** [comment]
@marksweiss Thanks for pointing it out! Gonna have a fix deployed shortly. Safari 5 has this issue when `'use strict'` is applied in JS files.
